/**
 * FUNCTIONS
 *
 * 0. DEFINITION & BACKGROUND
 * 
 * 1. TWO PHASES TO USING FUNCTIONS:
 * 
 * 2. PARAMETER VS ARGUMENTS
 * 
 * 3. SYNTAX FOR A NAMED FUNCTION
 * 
 * 4. ASSIGNING A FUNCTION TO A VARIABLE
 * 
 * 5. SPECIFYING INPUTS AND OUTPUTS
 * 
 * 6. SCOPE
 * 
 * 7. CLOSURES
 * 
 * 
 * FUNCTION DECLARATION
 * 
 * FUNCTION EXPRESSION
 * Variable pointing to a function
 */