/**
 * LOOPS
 * 
 * 0. DEFINITION & BACKGROUND
 * 
 * 1. WHILE, FOR, FOR-IN LOOPS
 * 
 * 2. LOOPING X NUMBER OF TIMES, FORWARD COUNTING TO A LIMIT, BACKWARD COUNTING TO 0
 * 
 * 3. LOOP OVER AN ARRAY FORWARD AND BACKWARD
 * 
 * 4. LOOP OVER AN OBJECT
 */